workspace(
    name = "typescript_project"
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load("//:repositories.bzl", "typescript_project_repositories")
typescript_project_repositories()

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")
rules_js_dependencies()

load("@aspect_rules_ts//ts:repositories.bzl", "rules_ts_dependencies")
rules_ts_dependencies(
    ts_version_from = "//:package.json",
)

load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")
nodejs_register_toolchains(
    name = "nodejs",
    node_version = "18.12.1",
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock", "pnpm_repository")

npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    update_pnpm_lock = True,
    data = ["@//:package.json"],
)

load("@npm//:repositories.bzl", "npm_repositories")
npm_repositories()

pnpm_repository(name = "pnpm")
